\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{flipit}[2023/06/30 Flipit Class]


\LoadClass[12pt,letterpaper,twoside]{article}

\RequirePackage[hidelinks]{hyperref}
\RequirePackage{amsmath}
\RequirePackage{graphicx} % Required for inserting images
\RequirePackage{lipsum}
\RequirePackage{afterpage}
\RequirePackage{geometry}
\RequirePackage{fancyhdr}
\RequirePackage{enumitem}
\RequirePackage{xcolor}
\RequirePackage{bookmark}
\RequirePackage{subfiles}
\RequirePackage[explicit]{titlesec}

\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    urlcolor=blue
}

\geometry{top=1in, bottom=1in, inner=1in, outer=1in}


\RequirePackage{style}
\endinput